"""The assumption register — every input the economics consumes, with its status.

This is the module that decides which numbers are allowed on a slide.

`src/config.py` tags physical constants [DATASET] / [DERIVED] / [ASSUMED].
Economics needs one more tag than physics did, because it reaches for quantities
that are not ours to derive at all — a workover cost, a hydrogen price. Those get
[UNVERIFIED], and the rule attached to that tag is absolute: an UNVERIFIED
quantity may be swept, and may never be reported as a point value.

`Build_Plan.md` explains why the bar is set here rather than at "sounds about
right": the project's own `Data_sources_research.md` was AI-generated and shipped
fabricated datasets and an inverted viscosity claim. The instruction it drew from
that was: do not accept a price figure from anyone, including a model, without a
source you have opened. Nobody on this team has opened a source for a workover
cost, so no workover cost gets a point value.

WHAT SURVIVES THE RULE

Very little, and that is the point. The quantities that come out MEASURED are the
ones we generated ourselves on held-out data — classifier skill, the surrogate's
degradation against the simulator, screening latency. The economics is built so
that its headline output depends only on those, and the UNVERIFIED quantities
enter only as swept ranges that shape the envelope around it.

Usage:
    python -m src.economics.assumptions
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from enum import Enum

from src import config as C


class Status(str, Enum):
    """Provenance of a quantity. Ordered from strongest to weakest."""

    DATASET = "DATASET"        # straight out of the Mao et al. simulations
    MEASURED = "MEASURED"      # we measured it ourselves, on held-out data
    DERIVED = "DERIVED"        # computed from DATASET/MEASURED quantities
    ASSUMED = "ASSUMED"        # a documented modelling choice, swept
    UNVERIFIED = "UNVERIFIED"  # no source we have opened. SWEPT ONLY, NEVER A POINT.

    @property
    def quotable_as_point(self) -> bool:
        """May this appear on a slide as a single number?"""
        return self is not Status.UNVERIFIED


@dataclass(frozen=True)
class Quantity:
    """One input to the economics, with everything needed to defend it."""

    name: str
    status: Status
    unit: str
    source: str
    value: float | None = None
    low: float | None = None
    high: float | None = None
    note: str = ""

    def __post_init__(self) -> None:
        if self.status is Status.UNVERIFIED:
            assert self.low is not None and self.high is not None, (
                f"{self.name} is UNVERIFIED and must carry a sweep range")
            assert self.value is None, (
                f"{self.name} is UNVERIFIED and must not carry a point value — "
                f"got {self.value}. This is the check that keeps an invented "
                f"number off a slide; fix the register, not this assertion.")
        else:
            assert self.value is not None, f"{self.name} needs a value"

    @property
    def span_decades(self) -> float | None:
        """Orders of magnitude spanned by the sweep, for ranking uncertainty."""
        if self.low is None or self.high is None or self.low <= 0:
            return None
        import math
        return math.log10(self.high / self.low)


# ---------------------------------------------------------------------------
# MEASURED — generated by this project on held-out data. These carry the result.
# ---------------------------------------------------------------------------

MEASURED = [
    Quantity(
        name="pr_auc_simulator",
        status=Status.MEASURED,
        unit="PR-AUC",
        value=0.9941477096825486,
        source="outputs/source_comparison.json — 150 held-out simulations, "
               "15,911 aligned rows, horizon 3 (6 months)",
        note="Screen skill when the fields come from the simulator itself. "
             "The ceiling our own surrogate is measured against.",
    ),
    Quantity(
        name="pr_auc_surrogate",
        status=Status.MEASURED,
        unit="PR-AUC",
        value=0.984245783563486,
        source="outputs/source_comparison.json — same rows, U-Net fields",
        note="Screen skill in the configuration we would actually deploy. "
             "99.0% retention of the simulator's skill.",
    ),
    Quantity(
        name="pr_auc_persistence",
        status=Status.MEASURED,
        unit="PR-AUC",
        value=0.02175050749710928,
        source="outputs/xgb_results.json — horizon 3, persistence baseline",
        note="'Assume next period looks like this one.' The honest floor for a "
             "6-month horizon, which sits at a different phase of the storage "
             "cycle. At horizons that are whole cycles this rises above 0.99 and "
             "the task stops being forecasting at all.",
    ),
    Quantity(
        name="positive_rate",
        status=Status.MEASURED,
        unit="fraction",
        value=0.019357677549123764,
        source="outputs/source_comparison.json",
        note="Base rate of elevated-leakage rows under our own T3 label at the "
             "90th-percentile flux threshold. NOT a real-world fault base rate — "
             "it is a property of where we drew the threshold.",
    ),
    Quantity(
        name="assessment_latency_s",
        status=Status.MEASURED,
        unit="s per 20 hypotheses",
        value=7.9,
        source="Timed against the deployed API, 2026-08-14: POST /v1/assessments, "
               "simulation 0, timestep 31, 20 sampled faults, warm instance",
        note="Wall clock including network, on a Render free tier at 0.1 CPU. "
             "A pessimistic basis for a unit cost, which is the useful direction.",
    ),
    Quantity(
        name="hypotheses_per_field_prediction",
        status=Status.DERIVED,
        unit="count",
        value=20000.0,
        source="docs/PRESENTATION_CONTEXT.md — 1,000 realisations x 20 fault "
               "draws per realisation",
        note="The coverage the decoupling buys: the fault is not an input to the "
             "U-Net, so one field prediction is re-scored against every fault "
             "hypothesis without re-running the field.",
    ),
]

# ---------------------------------------------------------------------------
# ASSUMED — documented modelling choices. Swept, but defensible as mid-range.
# ---------------------------------------------------------------------------

ASSUMED = [
    Quantity(
        name="prior_bad_fault",
        status=Status.ASSUMED,
        unit="probability",
        value=0.10,
        low=0.01,
        high=0.40,
        source="No published base rate exists for conductive faults at candidate "
               "storage sites. Swept across the full plausible span.",
        note="The prior that a site harbours a fault conductive enough to matter. "
             "Swept because the VOI answer genuinely depends on it — a screen is "
             "worth nothing at a site nobody doubted and nothing at a site nobody "
             "would approve.",
    ),
    Quantity(
        name="hypotheses_simulated_unaided",
        status=Status.ASSUMED,
        unit="count",
        value=2.0,
        low=1.0,
        high=5.0,
        source="Inferred from simulator runtime: a full-physics run is multi-hour, "
               "so a screening campaign affords a handful of scenarios.",
        note="The number of fault scenarios an operator can afford to simulate "
             "without us. This is the quantity our coverage is compared against, "
             "so the comparison is stated as a range, not a strawman of one.",
    ),
]

# ---------------------------------------------------------------------------
# UNVERIFIED — no source we have opened. Swept only. Never a point value.
# ---------------------------------------------------------------------------

UNVERIFIED = [
    Quantity(
        name="mitigation_to_loss_ratio",
        status=Status.UNVERIFIED,
        unit="dimensionless",
        low=1e-4,
        high=1e-1,
        source="NO SOURCE OPENED. Would require a workover/appraisal cost and a "
               "containment-failure cost, neither of which we have a citation for.",
        note="The only economic parameter the headline result depends on, and it "
             "enters as a ratio, so both unknown costs cancel to one unknown "
             "number — which we then sweep over three decades rather than pick.",
    ),
    Quantity(
        name="hydrogen_price_usd_per_kg",
        status=Status.UNVERIFIED,
        unit="USD/kg",
        low=1.0,
        high=8.0,
        source="NO SOURCE OPENED. Build_Plan.md flags this as needing a real "
               "citation and it never got one.",
        note="Not consumed by the headline result. Listed so the register is "
             "complete and so the omission is visible rather than quiet.",
    ),
    Quantity(
        name="workover_cost_usd",
        status=Status.UNVERIFIED,
        unit="USD",
        low=1e5,
        high=1e6,
        source="NO SOURCE OPENED. Order-of-magnitude folklore in Build_Plan.md.",
        note="Not consumed by the headline result — it cancels into "
             "mitigation_to_loss_ratio.",
    ),
]

REGISTER: list[Quantity] = MEASURED + ASSUMED + UNVERIFIED
BY_NAME: dict[str, Quantity] = {q.name: q for q in REGISTER}


def get(name: str) -> Quantity:
    return BY_NAME[name]


def audit() -> dict:
    """Check the register obeys its own rules, and report what the result rests on."""
    for q in UNVERIFIED:
        assert not q.status.quotable_as_point
        assert q.value is None, f"{q.name} smuggled in a point value"

    names = [q.name for q in REGISTER]
    assert len(names) == len(set(names)), "duplicate quantity in the register"

    return {
        "counts": {s.value: sum(1 for q in REGISTER if q.status is s) for s in Status},
        "headline_depends_on": {
            "measured": [q.name for q in MEASURED],
            "assumed_swept": [q.name for q in ASSUMED],
            "unverified_swept": ["mitigation_to_loss_ratio"],
        },
        "never_point_quoted": [q.name for q in UNVERIFIED],
    }


def to_json() -> dict:
    return {
        "register": [
            {
                "name": q.name,
                "status": q.status.value,
                "unit": q.unit,
                "value": q.value,
                "low": q.low,
                "high": q.high,
                "span_decades": q.span_decades,
                "quotable_as_point": q.status.quotable_as_point,
                "source": q.source,
                "note": q.note,
            }
            for q in REGISTER
        ],
        "audit": audit(),
    }


def main() -> int:
    report = to_json()

    print(f"{'quantity':<34} {'status':<11} {'value / range':>26}  unit")
    print("-" * 92)
    for q in REGISTER:
        if q.value is not None:
            shown = f"{q.value:,.6g}"
        else:
            shown = f"{q.low:,.4g} .. {q.high:,.4g}"
        flag = "" if q.status.quotable_as_point else "  <- SWEEP ONLY"
        print(f"{q.name:<34} {q.status.value:<11} {shown:>26}  {q.unit}{flag}")

    a = report["audit"]
    print(f"\nCounts: " + "  ".join(f"{k} {v}" for k, v in a["counts"].items() if v))
    print(f"\nThe headline result (screen efficiency) consumes only:")
    print(f"  measured:          {', '.join(a['headline_depends_on']['measured'][:3])}, ...")
    print(f"  assumed, swept:    {', '.join(a['headline_depends_on']['assumed_swept'])}")
    print(f"  unverified, swept: {', '.join(a['headline_depends_on']['unverified_swept'])}")
    print(f"\nNever quoted as a point value: {', '.join(a['never_point_quoted'])}")

    C.OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    out = C.OUTPUT_DIR / "assumption_register.json"
    out.write_text(json.dumps(report, indent=2))
    print(f"\nWrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
