/* HyLeakAI portfolio and dynamics companion.  This is deliberately kept
 * separate from the screening workspace: it makes the synthetic-realisation
 * provenance explicit and does not turn the portfolio into a geographic map. */
(() => {
  const API = location.hostname.endsWith("github.io") ? "https://hyleakai-fcbszu3ruq-el.a.run.app" : "";
  const q = (selector) => document.querySelector(selector);
  const style = document.createElement("style");
  style.textContent = `
    .portfolio{margin:0 0 16px;padding:17px;background:#0b1715;border:1px solid #27403a}
    .portfolio-head{display:flex;justify-content:space-between;gap:16px;align-items:start}.portfolio h2{font-size:18px;margin:0 0 4px}.portfolio p{color:#9daca5;margin:0;font-size:13px}.portfolio canvas{width:100%;max-height:360px;display:block;margin-top:14px;border:1px solid #27403a;background:#07100e}.portfolio-legend{display:flex;justify-content:space-between;font:10px ui-monospace,monospace;color:#9daca5;margin-top:7px}.portfolio-note{font:11px ui-monospace,monospace;color:#9daca5;margin-top:9px}.slab-wrap{display:grid;grid-template-columns:minmax(220px,.6fr) 1fr;gap:14px;margin-top:14px}.slab-wrap canvas{margin:0;min-height:235px}.slab-copy{padding:13px;background:#11221f;border:1px solid #27403a}.slab-copy strong{display:block;margin:7px 0;font:600 18px ui-monospace,monospace}@media(max-width:700px){.portfolio-head{display:block}.slab-wrap{grid-template-columns:1fr}}
  `;
  document.head.append(style);
  const el = document.createElement("section");
  el.className = "portfolio";
  el.innerHTML = `<div class="portfolio-head"><div><div class="eyebrow">Portfolio explorer / stage 1</div><h2>1,000 synthetic geological realizations</h2><p>Colour represents suitability score; click a highlighted point to take its held-out realization into the live field explorer.</p></div><span class="tag" id="portfolio-state">Loading ranking</span></div><canvas id="portfolio-cloud" width="1100" height="360" aria-label="Suitability cloud of synthetic geological realizations"></canvas><div class="portfolio-legend"><span>Low suitability</span><span>capacity → &nbsp; | &nbsp; seal risk ↑</span><span>High suitability</span></div><div class="portfolio-note" id="portfolio-note">Only outlined points are held-out realizations available to the deployed U-Net. Other points remain portfolio context, not selectable live fields.</div><div class="slab-wrap"><canvas id="dynamic-slab" width="460" height="300" aria-label="Animated interpretive reservoir slab for the selected U-Net saturation field"></canvas><div class="slab-copy"><div class="eyebrow">Dynamics companion / stage 2</div><h2>Reservoir slab</h2><p>Interpretive 3D companion to the authoritative 2D field map. It redraws from the selected U-Net saturation field whenever the selected realization or timestep changes.</p><strong id="slab-step">Waiting for field</strong><p id="slab-summary">Use the portfolio cloud or the configuration controls to select a held-out realization.</p></div></div>`;
  q(".grid").before(el);
  const canvas = q("#portfolio-cloud"), ctx = canvas.getContext("2d"), slab = q("#dynamic-slab"), sctx = slab.getContext("2d");
  let points = [], live = new Set(), selected = null, currentFields = null;
  function colour(t){ return `hsl(${210 - 100 * t},${55 + 25*t}%,${28 + 32*t}%)`; }
  function drawCloud(){
    const W=canvas.width,H=canvas.height,p={l:54,r:22,t:22,b:38};ctx.clearRect(0,0,W,H);ctx.strokeStyle="#27403a";ctx.lineWidth=1;
    for(let i=0;i<6;i++){let x=p.l+i*(W-p.l-p.r)/5,y=p.t+i*(H-p.t-p.b)/5;ctx.beginPath();ctx.moveTo(x,p.t);ctx.lineTo(x,H-p.b);ctx.stroke();ctx.beginPath();ctx.moveTo(p.l,y);ctx.lineTo(W-p.r,y);ctx.stroke();}
    ctx.fillStyle="#9daca5";ctx.font="11px ui-monospace,monospace";ctx.fillText("seal risk",6,18);ctx.fillText("capacity",W-82,H-10);
    points.forEach(point=>{let x=p.l+point.capacity_norm*(W-p.l-p.r),y=H-p.b-point.seal_risk_norm*(H-p.t-p.b);ctx.fillStyle=colour(point.suitability_score/100);ctx.globalAlpha=live.has(point.sim_id)?.95:.22;ctx.beginPath();ctx.arc(x,y,live.has(point.sim_id)?3.1:1.8,0,Math.PI*2);ctx.fill();if(selected===point.sim_id){ctx.globalAlpha=1;ctx.strokeStyle="#fff";ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,6,0,Math.PI*2);ctx.stroke();}});ctx.globalAlpha=1;
  }
  function hit(event){const r=canvas.getBoundingClientRect(),x=(event.clientX-r.left)/r.width*canvas.width,y=(event.clientY-r.top)/r.height*canvas.height,p={l:54,r:22,t:22,b:38};let best=null,d=Infinity;points.forEach(v=>{if(!live.has(v.sim_id))return;let px=p.l+v.capacity_norm*(canvas.width-p.l-p.r),py=canvas.height-p.b-v.seal_risk_norm*(canvas.height-p.t-p.b),dd=(px-x)**2+(py-y)**2;if(dd<d){d=dd;best=v}});if(best&&d<225){selected=best.sim_id;drawCloud();const select=q("#simulation");select.value=String(best.sim_id);select.dispatchEvent(new Event("change"));q("#portfolio-note").textContent=`Selected held-out realization #${best.sim_id}: suitability ${best.suitability_score.toFixed(1)} / 100; capacity ${best.capacity_norm.toFixed(2)}, seal risk ${best.seal_risk_norm.toFixed(2)}, heterogeneity ${best.heterogeneity_norm.toFixed(2)}.`;}}
  function drawSlab(){if(!currentFields)return;const d=currentFields.layers.saturation,rows=d.values,N=rows.length,W=slab.width,H=slab.height;sctx.clearRect(0,0,W,H);sctx.fillStyle="#07100e";sctx.fillRect(0,0,W,H);const ox=70,oy=50,ww=300,hh=170;for(let y=0;y<N;y+=2)for(let x=0;x<N;x+=2){const v=rows[y][x],px=ox+(x/N)*ww+(y/N)*42,py=oy+(y/N)*35; sctx.fillStyle=`rgba(30,${Math.round(70+170*v)},${Math.round(95+110*v)},${.15+.85*v})`;sctx.fillRect(px,py,Math.ceil(ww/N*2)+1,Math.ceil(hh/N*2)+1)}sctx.strokeStyle="#9daca5";sctx.strokeRect(ox,oy,ww+42,hh+35);sctx.fillStyle="#9daca5";sctx.font="11px ui-monospace,monospace";sctx.fillText("caprock",ox,25);sctx.fillText("H₂ saturation / U-Net field",ox,H-16);const peak=Math.max(...rows.flat());q("#slab-step").textContent=`Timestep ${currentFields.timestep} • H₂ max ${peak.toFixed(2)}`;q("#slab-summary").textContent=`Interpretive slab from real 128 × 128 saturation values for synthetic realization #${currentFields.simulation_id}.`}
  async function fetchFields(){const sim=q("#simulation").value,t=q("#timestep").value;if(!sim||sim==='Loading…')return;try{currentFields=await (await fetch(`${API}/v1/fields/${sim}?timestep=${t}&layers=saturation`)).json();if(!currentFields.layers)throw Error("field response unavailable");drawSlab()}catch(e){q("#slab-summary").textContent="Field could not be refreshed."}}
  canvas.addEventListener("click",hit);q("#simulation").addEventListener("change",fetchFields);q("#timestep").addEventListener("change",fetchFields);
  (async()=>{try{const response=await fetch(`${API}/v1/suitability`);if(!response.ok)throw Error(response.status);const data=await response.json();points=data.points;live=new Set(data.live_simulation_ids);q("#portfolio-state").textContent=`${points.length} ranked • ${live.size} live`;drawCloud();fetchFields()}catch(e){q("#portfolio-state").textContent="Ranking unavailable";q("#portfolio-note").textContent="The suitability portfolio could not be loaded from the API."}})();
})();
